# Useful commands:
# Prefix + & - close window
# Prefix + % - (with shift), split horizontal
# Prefix + " - (with shift), split vertical
#
# Reload with: tmux source-file ~/.tmux.conf

source-file ./mouse.conf
source-file ./keys.conf
source-file ./style.conf
