# Useful commands:
# Prefix + & - close window
# Prefix + % - (with shift), split horizontal
# Prefix + " - (with shift), split vertical
#
# Reload with: tmux source-file ~/.tmux.conf

set -g mouse on

# Keys
bind | split-window -h \; split-window -v

# Style & Format
set -g status-style "fg=#aaaaaa,bg=colour235"
set -g base-index 1
set -g pane-base-index 1

# Status bar format
set -g window-status-format " #I:#W  "
set -g window-status-current-format ">#[fg=#ffffff]#I:#W#[default]< "
