# Style & Format
set -g status-style "fg=#666666,bg=black"

# Status bar format
set -g status-interval 5
set -g window-status-format " #[fg=colour243,bg=black] #W "
set -g window-status-current-format " #[fg=colour33,bg=black]#[fg=black,bg=colour33] #W #[fg=colour33,bg=black]"
set -g status-right "#[fg=colour238,bg=black]#[fg=colour252,bg=colour238] #(echo '#{pane_current_path}' | rev | cut -d'/' -f1-2 | rev) "
