# Style & Format
set -g status-style "fg=#666666,bg=black"

# Status bar format
set -g status-interval 5
set -g status-justify left
set -g status-left-length 100
set -g status-left '#[fg=colour250,bg=#{?client_prefix,#8D00B8,colour235}] #S #[fg=#{?client_prefix,#8D00B8,colour235},bg=black]'
set -g window-status-format " #[fg=colour243,bg=black] #I:#W#{?window_zoomed_flag, 󰁌,} "
set -g window-status-current-format " #[fg=colour33,bg=black]#[fg=black,bg=colour33] #I:#W#{?window_zoomed_flag, 󰁌,} #[fg=colour33,bg=black]"
set -g status-right-length 100
set -g status-right "#[fg=colour235,bg=black]#[fg=colour250,bg=colour235] #(echo '#{pane_current_path}' | rev | cut -d'/' -f1-2 | rev) "
