# Keys

# Main Dev Split
bind \\ split-window -h -p 30 \; send-keys "\\" Enter C-l \; split-window -v \; send-keys "\\" Enter C-l \; select-pane -t 1
bind | kill-pane -a -t 1

# Reload tmux conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# List session/pannels and folder and program
# NOTE: Disable for now. Can use the zsh function `tlist`. Simpler and work everywhere.
# bind m send-keys "tmux list-panes -a -F '#{?session_attached,ATTACHED,DETACHED} #S:#I.#P \"#{window_name}\" #{pane_current_path} #{pane_current_command}'" Enter

# Clear right panels
bind C send-keys -t 2 "clear" Enter "\\" Enter C-l \; send-keys -t 3 "clear" Enter "\\" Enter C-l

# Pane nav
bind-key o select-pane -t :.+ # already default
bind-key O select-pane -t :.-

# Clear current pane
bind k send-keys "clear" Enter "\\" Enter C-l

# Kill pane (remove the 'confirm-before')
bind x kill-pane

# Kill session
bind X kill-session
