# Keys

# Main Dev Split
bind | split-window -h -p 40 \; send-keys "\\" Enter C-l \; split-window -v \; send-keys "\\" Enter C-l \; select-pane -t 1

# Reload tmux conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Skill sesion
bind X kill-session

# Kill all unattached sessions
bind C run-shell "tmux list-sessions -F '#S #{session_attached}' | awk '\$2 == 0 {print \$1}' | xargs -I {} tmux kill-session -t {}"
