# Keys

# Main Dev Split
bind | split-window -h -p 30 \; send-keys "\\" Enter C-l \; split-window -v \; send-keys "\\" Enter C-l \; select-pane -t 1

# Reload tmux conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# List session/pannels and folder and program
# NOTE: Disable for now. Can use the zsh function `tlist`. Simpler and work everywhere.
# bind m send-keys "tmux list-panes -a -F '#{?session_attached,ATTACHED,DETACHED} #S:#I.#P \"#{window_name}\" #{pane_current_path} #{pane_current_command}'" Enter

# Clear right panels
bind C send-keys -t 2 "\\" Enter C-l \; send-keys -t 3 "\\" Enter C-l

# Skill sesion
unbind x
bind x kill-session
