# Naming
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Style & Format
set -g status-style "fg=#666666,bg=black"

# Status bar format
set -g window-status-format " #[fg=colour252,bg=black] #W "
set -g window-status-current-format " #[fg=colour33,bg=black]#[fg=black,bg=colour33] #W #[fg=colour33,bg=black]"
