# Style & Format
set -g status-style "fg=#aaaaaa,bg=colour235"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Status bar format
set -g window-status-format " #I:#W  "
set -g window-status-current-format ">#[fg=#ffffff]#I:#W#[default]< "
