# Naming
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
# Use manual pane title (set via select-pane -T) as window name.
# Fallback to the current command if the title is just the default hostname or path.
set -g automatic-rename-format "#{?#{==:#T,#{host_short}},#{pane_current_command},#{?#{==:#T,#{host}},#{pane_current_command},#{?#{==:#T,#{pane_current_path}},#{pane_current_command},#T}}}"

# Popups
set -g popup-border-style "fg=#444444"

