
# Prefix Key (or use C-@ "alias" if issues)
set -g prefix C-k
unbind C-b
bind C-k send-prefix

# Mouse & Clipboard
set -g mouse on
set -g set-clipboard on

# Others
source-file ~/.config/tmux/keys.conf
source-file ~/.config/tmux/style.conf
source-file ~/.config/tmux/bar.conf
